### ISSUE TITLE
PMS Colors

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#101]
Will you please remind me of the pantone colors/numbers for the Epic website.  I can't find them.  Thanks!

**Comment by BigActual** [comment]
I don't recall defining them in Pantone because we were focused on the web. I'll add that in the future. Here's the way we put it together. There are certainly numeric conversions available, like this one: http://rgb.to/

Just type in the value you want to convert from, which are in this style tile, and you'll be all set.
![epic_style_tiles](https://cloud.githubusercontent.com/assets/8271108/22373424/c83fb3c6-e46f-11e6-8786-fe0e5f5bad01.jpg)

**Comment by evasolo** [comment]
​I guess that is why I couldn't find them.  This is helpful.  Thank you!​

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: www.epicraces.com e: eva@epicraces.com
