### ISSUE TITLE
Instagram link/icon on website

### ISSUE THREAD

**Issue by Peggyh1014** [realbig/RBM_TH_EPIC#104]
Eva would like to add the Instagram link and icon to the Epic website.

**Comment by brashrebel** [comment]
Where exactly on the site are you envisioning?

**Comment by Peggyh1014** [comment]
Is there space to put the logo in the same area as the FB and Twitter icons?

**Comment by brashrebel** [comment]
Not really the way it is arranged right now. We could experiment with some new ways of presenting those icons. Do you have any specific requests or guidance or should we use our best judgement?

**Comment by Peggyh1014** [comment]
Eva,

I contacted Kyle about adding the Instagram icon/link to the Epic website.

Kyle is asking for direction (see below). I don't feel comfortable making
this call.

Peggy

**Comment by Peggyh1014** [comment]
Eva would like you to use your best judgement for placing the social media icons on the website.  Thanks.

**Comment by d4mation** [comment]
The Instagram Icon is now in the header on your Live site! We also added a YouTube icon with your YouTube Channel in order to balance things out.

If only 3 icons were present, things would either be too small, too large, or lopsided. Having 4 icons stacked in groups of 2 works very well while not taking up too much room or overpowering the logo.

![image](https://cloud.githubusercontent.com/assets/7770631/22654449/c3d9e5fc-ec5a-11e6-96b8-a809d1b1d19b.png)

**Comment by Peggyh1014** [comment]
Good thinking. Thank you!
