### ISSUE TITLE
Event Categories showing as words

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_EPIC#124]
From the Document:

> We had talked about icons for duathlon, aquabike, etc.  Is there a reason there are words instead?

**Comment by d4mation** [comment]
@evasolo Icons show when expanding the “Featured Events” menu on the Home Page. Should they be showing elsewhere?

![image](https://user-images.githubusercontent.com/7770631/45319590-32211a80-b50e-11e8-931d-6516a8ba990c.png)

**Comment by evasolo** [comment]
Thank you for all of this, Eric. We can work from the Githubs as opposed to
the google doc.  Since there are so many, and there will be more, would you
be able to schedule a call for this week to talk through everything?

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by evasolo** [comment]
Regarding the icons, we had discussed having them on each of the tiles, but
instead we see words.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by BigActual** [comment]
Joel likely interpreted the request incorrectly. We can switch it from words to icons. 

@evasolo , if you don't mind, I'd like to keep Eric heads down, programming, instead of having a call. Writing out issues does three things to make your experience with us better; it allows you time to give a more complete picture of what is required, it keeps the programmer from making mistakes due to misinterpretation, and it keeps us from skipping requests or missing items.

**Comment by d4mation** [comment]
@evasolo 

How exactly would you like to see the icons implemented here? The way the icons work now, many of the individual icons are re-used. For example: Duathlon uses both the Run and Bike icons. 

But perhaps more importantly, the Virtual Category also uses the Run Icon. So that means that if an Event has both the Virtual and Run Categories (Like the The Original A2 Turkey Trot does) that means it would show the Run icon twice with a different color background behind each.

I figure this may be undesirable behavior. 

It also could be confusing with the Kids Category since Kids uses the same set of icons as Triathlon with only the background colors distinguishing them. While these would be less likely to occur concurrently, it would be difficult to know at a glance which was a Triathlon and which was a kid-friendly event.

Here's the first 4 featured Events with only Icons rather than showing text to illustrate what I mean. 

I can see why you want to add the Icons here, but I also really think that the text should stay for clarity for what the Icons mean.

![image](https://user-images.githubusercontent.com/7770631/45376384-ae2a6980-b5c5-11e8-884d-ccc838aba513.png)

**Comment by evasolo** [comment]
I appreciate your thoughts on reasons to leave the words. I am OK eliminating kids and virtual from these icons.  We are going to do something completely different with the virtual races and I'm not that worried about tagging our "live" races that have a virtual option.  Agreed that the words clarify the options to a newbie, but most wouldn't know duathlon or aquabike either. I'm going to go with my gut and go with the icons (eliminate kids and virtual) and if I find I want to change to words it will be my problem.  Thanks!

**Comment by d4mation** [comment]
This is now on Staging.

I adjusted it slightly so that only Categories that are in the Dropdown will show their icons, since as it was before, once you removed Virtual and Kids those would have still shown their Icons.

**Comment by d4mation** [comment]
@evasolo This need approval on Staging before it can be pushed Live.

**Comment by evasolo** [comment]
Icons on staging look good, you can push it live.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
This is now Live
