### ISSUE TITLE
Sort "Event" Pages into Alphabetical or Chronological Order

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#13]
Not sure what happened, but suddenly the event pages (not the public view, but when we go to edit the event pages) are in some strange order that neither Eva nor I can comprehend. The majority of our active events are on the second page, while events that are on hold or not yet renewed are near the top of the list when we click on Events -> Events.

It would be very helpful for us if the way the event pages present themselves were in alphabetical order. This way, we can quickly scroll down the list for the event we are seeking. If this isn't possible, can the events be sorted according to the date of their event? This way, the most current events are at the top and easy to find. 

Thanks!

**Comment by brashrebel** [comment]
@AnaHotaling did you know that you can sort them yourself? When looking at the list of events (or any other content type in the dashboard), you can click on the headings for any column and the results will sort based on that value. In this case, you want the entries to sort alphabetically by title so you can simply click on the word "Title" at the top of the first column.

**Comment by AnaHotaling** [comment]
Hey @brashrebel! Tried that... It doesn't work. I clicked on Start Date, and everything re-sorted with the 2014 Hornet Tri (presumably the oldest) at the top of the list. I wanted it in the reverse chronological order, so I clicked the little arrow right beside Start Date. The events once again re-sorted... and at first, everything looked like it was fine. But only two of our January events were at the top of the list. It then skipped to Splash and Dash (June), then back to the third January event, then skipped to the second March event, then our April event, then it went to our October event, then to the July 2015 birthday event Eva created for her husband (all these others so far have 2016 dates), then to one of our September events, then to three April 2015 training talks, then to a January and February training talk, then finally back to March 2016's Run 3.14 Pi... and you get the idea. Definitely NOT in chronological order and, as you can gather from this example, we haven't even reached our key events yet! Sorting alphabetically does work, but this includes hiatused events that we might one day renew (so we don't want to delete them). I suppose I could add a Z to their name. Both Eva and I would prefer the events sorted in true chronological order according to the listed race start date... but you see what happens. And all of our 2016 events have active dates, so there's no reason last year's training talks should have come first. Can you please fix this... and make it the default display? Thanks!

**Comment by brashrebel** [comment]
@AnaHotaling thanks for the detailed explanation. I do want to understand something first, before recommending a plan. Do you recognize that this sorting of the events in the backend is something that only you and Eva see and has no bearing on what visitors to the site see? The sorting is something that you as a user define so if you prefer to view things one way, you can do so and how I view them will be unaffected.

And so, if I understand you correctly, you are asking that the user preferences be overridden and that we modify that listing to work differently so that it will be more convenient for you and Eva to manage your 36 events. Am I understanding this correctly? I'm asking this because it is confusing to me how it is a priority. I could understand if you had hundreds of events but there's only 36 so no matter how much you modify and improve the sorting, you'll only be saving yourself a few seconds here and there. Once again, actual visitors to the site will not be affected in any way by what you're requesting.

I just feel a need to understand this better. Thanks for your help here.

**Comment by AnaHotaling** [comment]
Right! It's just for us. We'd like for the event listing, when we click on Events on the Dashboard, to come up chronologically, in the order of the date of the actual event. It makes it much easier for us to find an event so we can edit/modify/work on it. It may seem like it's only saving a few seconds (actually, more than a few seconds) -- it will make life a lot easier for us if we can easily locate the upcoming events instead of going, "Ah, there's Frosty... now where the heck is Pi Run? (scroll, scroll, scroll, scroll, scroll)... what on earth is it doing down there? Okay, where is A2 Marathon? It's not even on this page??? (Click). Oh, there it is!" 

Which is pretty much what I'm doing right now. I asked Eva about this and she noted that it drives her nuts, too, and to ask you do reorganize the events so we can find them more easily. Eva doesn't really modify the events much any more but, when she needs to do it, she wants them at her fingertips in date order since we all tend to think in date order when it comes to events! As for me, I'm trying to get Epic done while juggling my four other jobs, all of which I do from home on a 13-inch screen (okay, my husband set up an auxiliary screen for me, too) and it definitely would make my life easier to have everything right where I need it.

Thanks!

**Comment by brashrebel** [comment]
Ok, that makes sense and isn't a problem. What I can do is add this to our to-do list for next week and will need Eva's approval for one hour of billable time to enhance the listings in the backend as you've described.

**Comment by AnaHotaling** [comment]
Okay... time for me to ask for a clearer explanation (sorry)! Shouldn't the sorting mechanism actually function correctly? I'm not sure I understand why Epic would be charged to fix a function that isn't working properly. I'm pretty sure Eva would ask me that (but in more vibrant terms).

**Comment by brashrebel** [comment]
I definitely understand how you would see it that way. So the sorting function is actually a little misleading as it is using the published date instead of those custom values. That wouldn't be too challenging to modify. However, setting those sorting parameters by _default_ is overriding existing functionality in a way that is unique and is certainly a custom enhancement.

**Comment by AnaHotaling** [comment]
Okay, so it's not by start date but by creation date. That's definitely... interesting! Strange, though, because the Ann Arbor Marathon page is far newer than a lot of the 2015 hiatused events, but it shows up further down the list when it should be closer to the top. Oh well. I'll let Eva know.
