### ISSUE TITLE
Page Titles not going Full-Width

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#143]
Is there a reason that the words can't go all the way across the page?  I just created a page titled: Epic Races Ambassador Program.  It seems it should go all the way across the page as opposed to having the word Program on the next line.

**Comment by d4mation** [comment]
This is because Pages currently have support for a Sidebar which is not in use. 

I just pushed a small change so that if the Sidebar is not in use, the Page Template will assume to be full-width. But if the Sidebar is ever added back and you need to force a Page to be full-width, you can change that here: 

![image](https://user-images.githubusercontent.com/7770631/45550066-d3062300-b7f7-11e8-9a82-24cec5e4215a.png)
