### ISSUE TITLE
Comments showing as Pending; should have been disabled

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#144]
I noticed a bunch of "pending" questions on our dashboard.  It looks as though they came in after we got rid of that ability.  Is there someplace they are able to ask questions and then we don't even see them?
<img width="604" alt="screen shot 2018-09-14 at 7 17 36 am" src="https://user-images.githubusercontent.com/16295786/45547362-8cf89180-b7ee-11e8-9d38-aa18ae70e151.png">

**Comment by d4mation** [comment]
These all seem to be on Pages rather than Blog Posts.

There's no Comments Template on Pages from what I can see, but they may have still found a way to submit them. 

Should all Pages have Comments disabled? Are there any content Types that should have Comments Enabled? Perhaps Events?

I am thinking to go into the database and batch disable Comments per-Content Type if that is the case. But I want to know which should have it preserved, if any.

**Comment by BigActual** [comment]
All off per my notes. No interaction on the site. Only via email.

**Comment by d4mation** [comment]
Just updated every bit of content on the site to have Comments set to be disabled and set it so that all new content will have Comments disabled by default.

**Comment by evasolo** [comment]
No comments - never ever ever- they have plenty of conventional ways to get
in touch with us.

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com
