### ISSUE TITLE
Can we hide these from the backend since we aren't allowing folks to add questions?

### ISSUE THREAD

**Issue by evasolo** [realbig/RBM_TH_EPIC#149]
<img width="604" alt="screen shot 2018-09-14 at 7 17 36 am" src="https://user-images.githubusercontent.com/16295786/45680469-faffca00-bb08-11e8-8e77-222849b7d7da.png">

**Comment by BigActual** [comment]
Yes. The system has checkboxes for that on every page and post. Here is a link to a video that I created to show how to turn them off while authoring the item.
https://d.pr/v/55Ua1W

I can have Eric take a look at ensuring this is off by default after we're done with all of the post-launch adjustments?

**Comment by d4mation** [comment]
They are already all off as of #144 

These are all older comments, so I'd just need to find a way to either hide this panel in the dashboard or I'd have to delete all Comments in the database (Because if I deleted all Pending Comments, then it'd show Approved Comments here)

Which would you prefer, @evasolo?

**Comment by BigActual** [comment]
Thanks for clarifying, Eric.

**Comment by evasolo** [comment]
You can go ahead and delete all comments.  No need to keep an archive, we
had never intended for that to be a feature.  Thanks!

Be fit, be well, and keep smiling,

Eva Solomon
Founder and CEO  Epic Races, LLC

p: 734.585.7101 ext. 700 m: 734.678.5045 a: 600 South Wagner, Ann Arbor, MI
48103
w: epicraces.com <https://www.epicraces.com/> e: eva@epicraces.com

**Comment by d4mation** [comment]
All deleted 👍
