### ISSUE TITLE
Add Heart MI Run

### ISSUE THREAD

**Issue by maryepicraces** [realbig/RBM_TH_EPIC#161]
Can we add Heart MI Run (virtual) as a tile on the front page?

**Comment by BigActual** [comment]
Yes, so I can plan ahead, when will it be ready to publish/promote?

**Comment by maryepicraces** [comment]
It's ready now.

**Comment by BigActual** [comment]
I did put it back in place, but it's missing an image. I removed it so that you could add the images for the feature tile and for the event hero image. I've given you instructions for that in #163 

When those images are loaded, add it back to the featured tiles by clicking the Featured box in the race categories area. Unchecking the box removes it. Like this:
![image](https://user-images.githubusercontent.com/8271108/45928036-fd986000-bf0a-11e8-82dc-762616ebed74.png)

**Comment by maryepicraces** [comment]
Done, thanks!
