### ISSUE TITLE
change an url

### ISSUE THREAD

**Issue by marieepicraces** [realbig/RBM_TH_EPIC#166]
Can you tell me how to change the url for the HCC copy so that it reflects the previous name? We're ready to launch that now and I would rather not have to reset all links, everywhere.

I have tried to use the edit permalink function in the back-end but it keeps pushing me back to the name with "2" attached at the end.

Thanks

**Comment by BigActual** [comment]
You can't have two posts with the same URL. Go into the old one and change the URL to -old and then go into the new one and update the URL to what the new one should be.

**Comment by marieepicraces** [comment]
I've done that - several times. It doesn't seem to be working properly.


Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by marieepicraces** [comment]
The old one has been changed to "original" but I still can't change the new one.

**Comment by marieepicraces** [comment]
Looks like the name reverts back.

**Comment by marieepicraces** [comment]
But it seems to be redirecting to the new page?...

**Comment by BigActual** [comment]
May I take over?

**Comment by marieepicraces** [comment]
Actually, it seems to be working as a redirect so we may be fine.

**Comment by BigActual** [comment]
That's not ideal though

**Comment by marieepicraces** [comment]
Tried moving the original event to the trash and renaming but that still doesn't seem to allow me to rename the new page after the old. 

No rush to get back to me about this, as long as the re-direct is working for now. I have a meeting at noon and heading up north this afternoon so I'll check in again later. Thanks!

**Comment by d4mation** [comment]
@marieepicraces 

Renaming the Event isn't what you want to do in this case. You want to:

1. Change the URL on the _old Event_ to something different and hit "Update"
  - ![image](https://i.imgur.com/u9ylRXE.gif)
2. Move the old Event to the Trash
4. Change the URL on the _new Event_ to what you want it to be and hit "Update"

The redirects you were hitting is because WordPress keeps a history of past URLs for a piece of Content in order for old links that you may have added into another Page or something to still work. So you have to clear out that history in order for WordPress to allow you to use the original URL that you wanted to change it to.

I've gone ahead and fixed this for the Hot Cocoa Classic, so it no longer has the `-2` at the end anymore.

**Comment by d4mation** [comment]
As an example of the "keeping history of past URLs", https://epicraces.com/event/hot-cocoa-classic-2/ takes you to the new Event still automatically, but if you were to put something else at the end such as https://epicraces.com/event/hot-cocoa-classic-3 it gives you a 404 error.

When choosing a URL it is important to trash the old Event so that the history of the old Event is not considered when WordPress determines if the URL you choose for the new Event is "allowed".

**Comment by marieepicraces** [comment]
Thanks for the fix, Eric, but I _did_ use _all_ of the steps you outlined above.  Any idea why the fix didn't work for me?...
And, if url editing is going to be an issue going forward, what's your recommended way of changing the event pages over to the new format?

**Comment by d4mation** [comment]
Unfortunately, unless you change the event over to the New Format _all at once_, making a copy of it and doing the URL renaming may be your best bet. If you were to save it as a Draft half-way through, that un-Publishes the old version. 

I am pretty sure that you could still Preview your changes if you were to do it all at once, though. You just can't save it as a Draft to continue later.

I am not sure why that solution would not have worked for you. That is quite interesting.

**Comment by marieepicraces** [comment]
I wondered about that, too...unless it was the *order *in which I did the
steps?

I may try the copy event method once more and see if I can get the URL
change to work for me this time around. Otherwise, it's tricky to keep a
functioning site going while making the changes.

Thanks!

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
The order of the steps is very important, yes. Hopefully it works for you on the next one!
