### ISSUE TITLE
"View" and "Get Shortlink" no longer appear as options on the events pages and regular pages

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#47]
Just updated the A2 Marathon page and, when I went to click "View" the button was not there. Similarly, when I was creating a new Pre-Marathon Activities page, I went to click "View" and the button wasn't there, either. Upon inspecting, I saw that the "Get Shortlink" button was also missing.

**Comment by d4mation** [comment]
This is because your site has been updated to WordPress 4.4.2 and those buttons were removed from view within WordPress itself.

You can find the "View Event" button at the very top of your screen, or you can also click the Link just below the Event Title.

![image](https://cloud.githubusercontent.com/assets/7770631/12815916/6cedcc28-cb17-11e5-971a-e284fb1adfa7.png)

The Get Shortlink button I can restore for you.

**Comment by AnaHotaling** [comment]
Those darn upgrades! Yes please to the short link!

On Thursday, February 4, 2016, Eric Defore notifications@github.com wrote:

> Closed #47 https://github.com/realbig/RBM_TH_EPIC/issues/47 via fe273da
> https://github.com/realbig/RBM_TH_EPIC/commit/fe273da26d417774e5ae3272fde28e9ba83c2888
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/47#event-539143493.

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
