### ISSUE TITLE
Ban/Block Individual from Epic site

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#58]
Dan Projansky
Swimmerdude@comcast.net
98.220.117.188

**Comment by d4mation** [comment]
I have just set it so that whenever that IP Address or Email Address Comments, it will be sent straight to the Trash.

Blocking either from the site entirely would be less than ideal, as if he gets a new IP Address from his Internet Service Provider and someone else gets that IP Address, then they wouldn't be able to access the site at all. Blocking Comments (which he was using to deface the site anyway) should be more practical.

This can also be set to just place his comments in Moderation instead, so if you'd rather have that, let us know!

**Comment by AnaHotaling** [comment]
That works! Eva doesn't want to see his posts at all. Thanks!!

On Thursday, March 24, 2016, Eric Defore notifications@github.com wrote:

> I have just set it so that whenever that IP Address or Email Address
> Comments, it will be sent straight to the Trash.
> 
> Blocking either from the site entirely would be less than ideal, as if he
> gets a new IP Address from his Internet Service Provider and someone else
> gets that IP Address, then they wouldn't be able to access the site at all.
> Blocking Comments (which he was using to deface the site anyway) should be
> more practical.
> 
> This can also be set to just place his comments in Moderation instead, so
> if you'd rather have that, let us know!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/58#issuecomment-200963500

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
