### ISSUE TITLE
Gallery Button on Waterloo Grit and Gravel Page Not Working

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#59]
People are clicking the button, but nothing happens other than it going orange. I just checked and the link is connected to the button, but I have to hold down my mouse to select "Open in New Tab" to actually go to the link.

**Comment by d4mation** [comment]
Turns out it was due to some JavaScript on the page that facilitated the nice scrolling action to other parts of the page when clicking the other buttons. I added a bit of code to check for that, so now the Gallery Link should always work when it is an external link or linking to another page.

If you hard refresh, you should be good to go!

**Comment by AnaHotaling** [comment]
Thanks!!! Hopefully it was just that page... haven't checked the others!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
This was a pretty sweeping change, so it should automatically fix it anywhere that the problem previously existed. :+1:
