### ISSUE TITLE
Need "Photo Album" section added to event page template

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#63]
Eva would like a section in the event page template where we can post links to previous years' photos. That way, the Gallery button takes people to this year's photos and the Album, down further in the page, can take them to previous photos. Thanks!

**Comment by brashrebel** [comment]
Sounds like a nice idea. So all of these links are to an external site where the photos are?

**Comment by AnaHotaling** [comment]
Yes! They are all links to the photographers' own sites.

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
Then this should be pretty simple although the navigation is getting pretty crowded. Can we just have one link for photos which scrolls down to where links to all years including the most recent are listed? I'm quite certain users will get confused if they see a link to "Gallery" AND a link to "Photo Album". What's the difference?

**Comment by AnaHotaling** [comment]
Let me check with Eva!

On Monday, April 11, 2016, Kyle notifications@github.com wrote:

> Then this should be pretty simple although the navigation is getting
> pretty crowded. Can we just have one link for photos which scrolls down to
> where links to all years including the most recent are listed? I'm quite
> certain users will get confused if they see a link to "Gallery" AND a link
> to "Photo Album". What's the difference?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/63#issuecomment-208462708

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Eva says that yes, a link from the Gallery button to a section in the template where all photo links, current and past, are listed. Thanks!

**Comment by d4mation** [comment]
Since I figured that for different Events there may be different ways that the Photos Links may need to be displayed, I opted to put a WYSIWYG Editor in there. This provides the added ability to place additional description text in there as well as separating the Links into sections using Headers or other means if that is necessary.

If you have anything in the new editor box, it will override the old Photo Gallery Link. This way if there's only one Link, you can still use the old system just fine (And so this change won't affect any old Event pages).

Is there another way you'd rather it be implemented? I wanted to ensure that it fit your needs, while also staying flexible going into the future.

![image](https://cloud.githubusercontent.com/assets/7770631/14494519/310779d4-0159-11e6-820c-86131bb34bef.png)

![image](https://cloud.githubusercontent.com/assets/7770631/14494539/4abd024a-0159-11e6-8836-e0c42e5b4296.png)

**Comment by AnaHotaling** [comment]
Perfect!!!! Thank you!!!

Ummm... while I have you here, can the FAQ box be WSYIWYG, too? There are
times I need to include links to our Policies page, to our Race-Day Guide,
etc.

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by brashrebel** [comment]
I'd make a separate issue. We may need to discuss the pros and cons for something like that and I want to close this issue since it's done. Also, we're pretty much always "here" so don't worry too much about tacking on tasks when you have our attention. We'll get to it either way.
