### ISSUE TITLE
Turn off ability to comment on the Heart Hero Nomination Form

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#64]
I tried to edit this form so that there is no comment ability, but I couldn't find the option there. Could you please either turn off comments for this form or tell me how to do it so that I know how? Thanks!

**Comment by d4mation** [comment]
Could you link me to where you are using this Form on the site? I'm having a difficult time finding it on the frontend of the site.

**Comment by AnaHotaling** [comment]
Here you go, very last line of content on the page. I deleted the comment
already: http://epicraces.com/event/detroit-goddess/

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
It looks like you are linking to your Form from that Page. [Here's the Form's Page](http://epicraces.com/our-heart-heroes/heart-hero-nomination-form/).

From here, you may need to enable the ability to see **Discussion** Options from the `Edit Page` Screen By expanding `Screen Options` (The Comments checkbox just shows Comments left on the Page):
![image](https://cloud.githubusercontent.com/assets/7770631/14655516/a540197c-0650-11e6-8375-4e8fc4e25715.png)

From there, you can uncheck the ability for Visitors to add Comments:
![image](https://cloud.githubusercontent.com/assets/7770631/14655592/fa06fc50-0650-11e6-9724-b710520a694c.png)

I've gone ahead and disabled this for you. I just wanted to outline how to do it since you asked :)

**Comment by AnaHotaling** [comment]
Aha! Got it!!!! Thanks so much, for the explanation and for doing it for me!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
