### ISSUE TITLE
Change in recipient for form

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#65]
This one is mainly because I've never done it so I'm not sure how to do it. The Heart Hero Nomination Form data needs to go to mary@epicraces.com instead of to Eva now. Can you change this, or tell me how to do it? Thanks!

**Comment by d4mation** [comment]
This is in a different spot than the Comments, since the Comments were for the Page the Form was showing on. This would be a setting for the Form itself.

You need to go to `Forms` -> `Form Notifications` for your Form (You hover over `Settings` to see the different options) -> then Edit the `Admin Notification`

![image](https://cloud.githubusercontent.com/assets/7770631/14720159/0e15c37e-07ce-11e6-9ac1-5bcaf3973c52.png)

![image](https://cloud.githubusercontent.com/assets/7770631/14720077/a6f233e4-07cd-11e6-9807-3c305df52077.png)

From there, you just enter the new Email Address:

![image](https://cloud.githubusercontent.com/assets/7770631/14720094/bf59322a-07cd-11e6-969a-091ef3adc439.png)

I've taken care of this for you. Just wanted to show you how since you asked :)

**Comment by AnaHotaling** [comment]
Thank you! Got it! :)

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
