### ISSUE TITLE
Swim to the Moon Widget on STTM page looks AWFUL

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#66]
That pretty much describes it. Can you see what is going on, please?

**Comment by d4mation** [comment]
This has been fixed on your live site now. 

The way that the widgets on the Event Pages works is a bit unstable in that Crowdrise can decide to "break" it at any time. They are adding their own code directly into your Event Pages and we are doing what we can to change how it looks. They seem to have changed things up a bit and that's why it broke.

The main change that I can see is that the big "Donate" button was removed:

![image](https://cloud.githubusercontent.com/assets/7770631/14931566/8771b8e6-0e3a-11e6-9deb-ad02ec83e36a.png)

A good ol' hard refresh should show the new changes for you.

**Comment by AnaHotaling** [comment]
ACK!!!! Eva and I were just literally discussing that big DONATE button!
That's the reason she said to go ahead and get rid of the Charity Partner
thing, because people won't miss the big DONATE button on the Crowdrise
widget!  Can it be put back?

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Strangely, they seemed to have added that button back in...which alters how things were being displayed again:

![image](https://cloud.githubusercontent.com/assets/7770631/14954443/745124d8-1040-11e6-82e3-26e540603666.png)

I'll go ahead and revert the changes from Friday which should fix this again 👍
