### ISSUE TITLE
Cannot find where to re-order the home page's Crowdrise widgets

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#68]
I'd like to put the Crowdrise widgets on the home page in event order but couldn't figure out where on the Dashboard to go to do this...

**Comment by d4mation** [comment]
Unfortunately, this may not be possible given how Crowdrise's API currently works.

Here's a list of all the information we have access to for each Event that we pull down (Using Swim to the Moon as an example):

```
'event_id' => string '11842'
'event_name' => string 'Swim to the Moon'
'event_username' => string 'SwimtotheMoon'
'event_url' => string 'https://www.crowdrise.com/SwimtotheMoon'
'event_description' => string '<p>North Star Reach offers life-changing camp experiences for children with serious health challenges and their families...</p>'
'event_total_raised_online' => string '0.00'
'event_total_raised_offline' => string '0.00'
'event_donation_count_online' => null
'event_donation_count_offline' => null
'event_goal' => string '5000'
'event_photo' => string '/media/large/event_photo-5723d7a56b8ac.jpg'
```

Strangely enough, they don't provide any date information in the API Response.

Would the Events happen to be in the exact reverse order currently? If so I can easily reverse their order easily without needing extra data from Crowdrise. 

Otherwise, this will be something that we will need to get Crowdrise to add to the `get_events` API Response so that we have access to that data.

The only other way we could do this would be to specify the `event_id` for each event in the order that you'd want them to be displayed&mdash;which would not be ideal as the Event ID is pretty difficult to find under normal circumstances as I mentioned in #61 [here](https://github.com/realbig/RBM_TH_EPIC/issues/61#issuecomment-213076266).

**Comment by AnaHotaling** [comment]
Oh good heavens. No, they aren't in any order at all! They're all just
random. Ugh. I'll let Crowdrise know.

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
Here's what Crowdrise says:

Hey Ana, 

Happy Friday. 

I just heard back from our Director of Engineering, and he let me know that this would actually be a setting on your end of things. It shouldn't be connected to the event date at all, so it would just be a matter of arranging the widgets in whichever order you would prefer. 

Definitely let me know what your team says and I'll be ready to dig in. 

Thanks so much.

**Comment by d4mation** [comment]
Do they know we are using the API to make our own "widgets"? It sounds like they may think we're using the Widget Codes provided by them that you're using on the individual Event Pages and in that case you would just arrange them as needed.

Right now I'm just grabbing all the Events and outputting them in the order that they are received in since there's no usable information for me to sort it by (If they returned the Event Date for each event, I could sort them by Date easily)

Here's the relevant snippet from their documentation. About the only way we could sort it currently would be by giving it a list of Event IDs in the order that you want them in, but they don't make those easy to figure out on your end.

![image](https://cloud.githubusercontent.com/assets/7770631/15151509/655177ca-169f-11e6-8a4b-574acfd7f8eb.png)

**Comment by AnaHotaling** [comment]
I've forwarded this to Crowdrise. Hopefully they'll have an answer!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by AnaHotaling** [comment]
News from Crowdrise:

Happy Friday. Our Director of Engineering wanted me to let you know that we added event_date to the data returned by get_events. My understanding is that this should help you order everything. Can you pass this along to your team and let me know how it goes?

**Comment by d4mation** [comment]
Excellent! I'll take a peek and see what I can set up!

**Comment by d4mation** [comment]
I've gone ahead and added some Sorting Options to the Widget for sorting by Date!

It defaults to showing the Soonest Events first, but you can reverse it if you want to show the furthest away Events first if you'd like.

It should be showing them in the correct order now, but could you confirm that for me? I want to ensure it is in the order that you want them to be. It's all set up on your Live Site.

![image](https://cloud.githubusercontent.com/assets/7770631/15256156/24bbe76a-190e-11e6-82e6-0d0b821968da.png)

**Comment by AnaHotaling** [comment]
Can you tell me where I'm looking? I went to Appearance -> Widgets and got
lost.

On Friday, May 13, 2016, Eric Defore notifications@github.com wrote:

> I've gone ahead and added some Sorting Options to the Widget for sorting
> by Date!
> 
> It defaults to showing the Soonest Events first, but you can reverse it if
> you want to show the furthest away Events first if you'd like.
> 
> It should be showing them in the correct order now, but could you confirm
> that for me? I want to ensure it is in the order that you want them to be.
> It's all set up on your Live Site.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/7770631/15256156/24bbe76a-190e-11e6-82e6-0d0b821968da.png
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/realbig/RBM_TH_EPIC/issues/68#issuecomment-219107279

## 

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
There's two ways to access it:

Appearance -> Widgets -> Homepage Full -> Crowdrise Events

Or

Appearance -> Customize -> Widgets -> Homepage Full -> Crowdrise Events

Going through the "Customize" Menu allows you to view your changes in Real-Time, which I personally prefer.

**Comment by AnaHotaling** [comment]
Perfect! And it's all in the right order, too! THANK YOU!

Last question... when we add events, will this update automatically or do I
have to let you know?

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
No problem! 

It should update automatically. It grabs the newest data from Crowdrise via their API. It is possible there could be a slight delay due to caching on the Server, but that would be only a day in most cases.

I noticed that "Swim to the Moon" has added itself in now that it has a proper Event Photo and its donation total has updated without any interaction on our end :)

**Comment by AnaHotaling** [comment]
Hooray! Thanks, Eric!!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
