### ISSUE TITLE
Sponsors layout enhancements

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#7]
Currently, the way sponsor logos are arranged on single events is not adequate and the client isn't satisfied. We need to provide some alternative options and then implement. Here's what I want to see mocked up (just a screenshot of this concept for each, not necessary to build out):

A. Same basic layout as current, just with much more vertical and horizontal balance. We need all logos to be very aligned which is difficult since they're all different shapes and sizes and viewed on different screen widths but we need to get it done anyway. Use [this page](http://www.grandrapidstri.com/sponsorship/our-sponsors/) for inspiration.
B. Same as above basically but with a subtle box outline like [this](http://freepmarathon.com/sponsors) or [this](http://crim.org/races-events/crim/sponsors/). All boxes should align nicely and be the same size.
C. Somewhat of a different approach here. Instead of just logo, do logo with a paragraph of text describing the business immediately to the right. For full screens we could have to columns (two sponsors per row) if it fits, otherwise just 1 sponsor per row.

Let's get all 3 of these mocked up and inserted here so the client can provide their input.

**Comment by d4mation** [comment]
Here's A and B. 

I have it simplified down so that within each Tier:
- If there's 1 Partner, it is centered with a 33% width. 
- If there's 2 Partners, they both have 50% width.
- If there's 3 or more Partners, they all get 33% width.

I'm going to start on C now. I've got these all in their own Branches locally, so switching between designs should be fairly straightforward. It was easier for me to build it out now rather than to mock it up in the Inspector.

![image](https://cloud.githubusercontent.com/assets/7770631/11754447/7b6ce6ea-a019-11e5-96bc-c1b1c32dcb98.png)

![image](https://cloud.githubusercontent.com/assets/7770631/11754449/7f6836d2-a019-11e5-9dde-a98806d147a8.png)

**Comment by d4mation** [comment]
Here's C.

On Mobile I had it go down to 1 Sponsor per Row. 

On Desktop, if the Tier only has a single Sponsor it will show that Sponsor at a larger size (50% for the image, 50% for the description). Otherwise, it is 2 Sponsors per Row at 25% for the images and 25% for the descriptions.

For the Description Box I am having it grab `the_content` so that HTML is allowed and to avoid a word/character limit. If it becomes too long for the viewable space, it will gain a Scrollbar.

Desktop:
![image](https://cloud.githubusercontent.com/assets/7770631/11755515/f634f78a-a020-11e5-93c0-2a3191db6c6f.png)

Mobile: 
![image](https://cloud.githubusercontent.com/assets/7770631/11755528/faf9205c-a020-11e5-96f5-e86a4e825287.png)

**Comment by brashrebel** [comment]
I really like C although I don't love how it looks. I believe the description for each sponsor adds so much value both for the end user and for the sponsor. But I'm not a big fan of the text being in that darker colored box actually. I recognize that the layout gets destroyed if a description for a sponsor is too long so the scroll bar makes sense, however I think I'd prefer to just restrict the number of characters so they are forced to keep it brief. That said, I'm not even sure that's the layout we'll use.

B looks alright, though I'm wondering how it would look with only a colored `border` instead of `background-color`. Or maybe that could be option D.

**Comment by evasolo** [comment]
Agree with Kyle on C.  Love the idea, but so much is lost in design that it is distracting and loses the value we are trying to create.  I think the traditional link to the website is the best way to go.  One thought is if something could happen when they mouse over the image?  I like the uniform boxes in B, but for some reason it looks unfinished.  Maybe because they are gray?  A looks the cleanest to me right now, but wondering if B could be improved.  I noticed that the Grand Rapids inspiration has Charity Partners as a header within their sponsors.  I would be interested in doing that rather than giving them a separate box.  We are moving away from calling them charity "partners" and just calling them  featured charity or something like that.  Haven't set on a name yet.

**Comment by brashrebel** [comment]
@evasolo thanks for your input. If you want to adjust the way charity partners are displayed, can you create a new issue please? That way we can discuss that separately and resolve it independent of this issue.

I'd like to see how mockup B looks with just a border and not a background color. One of the inspiration sites did that too. The background color doesn't work mostly because these logos don't have transparent background. They have white backgrounds so it won't look good no matter what. If we were able to get all sponsors to provide us with logos with transparent backgrounds then they could look nice in any kind of box.

**Comment by d4mation** [comment]
Here's B without the Grey Background. I left the border on, but made it 1 pixel thicker:

![image](https://cloud.githubusercontent.com/assets/7770631/12034956/978bbc76-ae05-11e5-9fb6-e7b099dae501.png)

Here's C without the dark box surrounding the text. I also limited it to 50 words and then it gets cut off. I vertically centered the text as well since without the dark box, it looked weird being aligned to the top.

![image](https://cloud.githubusercontent.com/assets/7770631/12035269/04e34d0e-ae09-11e5-99c3-12e507cead5e.png)

@evasolo, currently when you Hover over one of the images, it becomes lighter and the mouse pointer changes to show that it is a Link to their Website. What would you like to see happen when a User Hovers over one of the images?

**Comment by evasolo** [comment]
I like the boxes without the gray background!

**Comment by d4mation** [comment]
It is all set on the website now!

Edit: You may need to hard-refresh your browser to see the changes.

CTRL+F5 on a Windows computer, or CMD+SHIFT+R on a Mac.

**Comment by AnaHotaling** [comment]
These look great!!!! Thanks!!!
