### ISSUE TITLE
Changes not sticking

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#72]
Over the past week, I made a bunch of changes to Tri Goddess Tri, the Firecracker 5K, and Swim to the Moon. Apparently, none of the changes stuck, even though I did exactly what I've always done (make the change, click Update). Eva noted last night that she had made some changes that I had already made, and she asked me to make other changes I had already done. I have no idea why none of my changes disappeared. I do know, for instance, that yesterday I made changes to the Swim to the Moon Race-Day Guide and hit Update. An hour later, I went to change something else... and my changes were gone. Any help with this would be MUCH appreciated!

**Comment by d4mation** [comment]
This is very interesting. I just tested this out on your Staging site using the same User Role that you have and I was able to edit the Swim to the Moon Race-Day Guide successfully and the changes showed up for me.

Were you logged in when you tried to view your changes on the website? It's possible that the changes were successful, but the Server was still holding a cache of the old content. I just cleared the Server caches so if that were the case it should be resolved now.

**Comment by AnaHotaling** [comment]
I was logged in. Weird, isn't it? Actually, come to think of it, I was
asked repeatedly to log in this past week, waaay more than usual... even
though I always keep the Remember Me box checked.

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Very weird indeed.

I've added some functionality to your site that should help me figure out what's going on. When you get the chance, could you attempt to edit and update a page on the site similarly to how you did before? I want to recreate the issue as closely as possible. 

It doesn't have to be a significant change; uppercasing a letter or adding in a space would be enough. Although it should ideally be a change we can notice on the website.

**Comment by AnaHotaling** [comment]
I just edited Tri Goddess Tri... I added a pink graphic at the right top of
the content of the page, plus all the changes I'd previously made. Will
that work?

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
This pink graphic here?
![image](https://cloud.githubusercontent.com/assets/7770631/16204086/2fab3e46-36eb-11e6-99a8-13c098546a4f.png)

I was able to see that change both while being logged in and while being logged out.

Could this be caused by your household server holding a cache of the webpage? I'm wondering if this is related to #26

**Comment by AnaHotaling** [comment]
Well.... it was also on my iphone and my iPad. Plus Eva made changes to TGT
and they were gone when I went in to add the pink graphic.

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
This is admittedly a long shot, but do you and/or @evasolo leave a bunch of tabs open in your web browser, including Page-Edit screens for your website, and then allow your computer to enter "Sleep Mode"?

Normally when you have a Page Edit window open and someone else tries to edit it, you are met with that little "So and so is editing this page, would you like to take over?" popup. However, if their computer is in sleep mode you wouldn't be able to tell that they have that page open. This is because their web browser isn't sending out a periodic message saying that they are currently editing that page as the computer is in Sleep Mode.

We're thinking that this may have been caused by one of you having the tab open on your computer and having it go into sleep mode while the other had gone in and edited it. Then once the other opened their computer to check, it seemed like the changes weren't there. 

---

Another possibility is that while the changes were being saved, did you try to navigate away before it finished? It may seem counter-intuitive, but the data actually saves once the page reloads and then it shows the success message. If that success message didn't have a chance to show it is possible that the data never saved.

**Comment by AnaHotaling** [comment]
Hmmmmmm. I know that I wait for the page to update. Yesterday that darned
Update button took forever to finally become solid again before jumping to
the top of the page (when it updates, it does that, but you knew that
already)!

BUT! I do leave tabs on my browser open 24/7. But I do wait for the Update
button and the jump to the page top to show things have been saved, so
shouldn't my changes be saved? Even if Eva's page is in sleep mode? OH!
Except that when she goes to edit it, she'll save what is most recent on
her screen, which isn't what is on my screen. I get it!

Except that I pulled up the TGT page fresh this morning (the tab had been
left on Firecracker 5K) so Eva's changes should have been in there, and
they weren't... she'd changed all the "pasta dinner" mentions to "pasta in
the park," and these were nowhere.

Weird.

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
That is really strange. It sounds like everything should be going smoothly and proper precautions are being made.

From my end it looks like you've been successfully updating a bunch of things and the changes have been going through. From now on we should be able to monitor this to see what, if anything, goes wrong with this.
![image](https://cloud.githubusercontent.com/assets/7770631/16206797/080a253e-36f8-11e6-89f1-f56e7ac0fe1a.png)

**Comment by AnaHotaling** [comment]
Okay! And if I notice that something has vanished, I'll let you know.
Thanks!!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/
