### ISSUE TITLE
Pasta Dinner Purchase Error

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#73]
We've received three emails so far today from people receiving Error 525 - Unable to create order when they try to buy pasta dinner tickets for Tri Goddess. It worked for me, so I'm telling everyone to clear their browser history and dump their cache and try again. Was there a server hiccup or is there something causing this?

**Comment by AnaHotaling** [comment]
Just heard from one of the clear-your-history ladies. Still getting the error on Chrome and and IE.

**Comment by d4mation** [comment]
This sounds like it is a communication issue between the site and PayPal for payment.

I just tweaked some things on the backend which should hopefully bring things in line with some recent changes within the past week or so on PayPal's side. Payments should go through properly now since we're forcing things to communicate the way PayPal likes it now 👍
