### ISSUE TITLE
Duplicating a Page

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#79]
Is there anyway to select a page and duplicate it? The Red Dress Dash Virtual Race Bag is going to be exactly the same as the Battle of Waterloo Virtual Race Bag, other than changing the name of the race and the graphic at the top. Instead of having to build it from scratch, I was hoping to just duplicate the Battle of Waterloo Virtual Race Bag... but when I went to copy the source, it only gave me the content I'd input, not the actual components of the goodie bag.

**Comment by brashrebel** [comment]
We don't have a built in feature for easily duplicating one. However we could implement it in about a half hour of billable time.

**Comment by AnaHotaling** [comment]
LOL! I'll check with Eva when she's back. I don't think I've really had a
cause to duplicate until now. :)

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
This functionality has now been added to your site. If you hit "Duplicate Page", it will create a copy of whatever content it was (Without any added Comments) and make it into a Draft. 

![image](https://cloud.githubusercontent.com/assets/7770631/21393051/be990038-c760-11e6-8189-3e939ddaba59.png)

You can then change the Title or whatever else you need to change without worries. (In the case of something like the Battle of Waterloo Good Bag, also be sure to change the Page Parent!)

You will want to ensure you update the Permalink like in the .GIF below after you've duplicated the Page so that it doesn't say the wrong thing.

![image](http://i.imgur.com/QVBWZLe.gif)

This will work on any Content Type on the site, so this can be utilized for Events or Staff as well.

**Comment by AnaHotaling** [comment]
Excellent!!!! Thank you!!!!
