### ISSUE TITLE
Back Orders on WooCommerce

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#80]
I set our Battle of Waterloo long-sleeved tech shirt to accept back orders. Tonight, we received emails from people who tried to place orders for out-of-stock sizes. The system would not allow them to place back orders. I just checked settings again, and it is indeed on Allow Back Orders. Any idea what went wrong?

**Comment by brashrebel** [comment]
That sounds strange. We'll take a look first thing next week.

**Comment by d4mation** [comment]
I'm playing around with this on your Staging Site and things seem to be working correctly. I've been able to add it to my Cart and I'm waiting on my developer account for PayPal to process so I can properly test "payment" (So I will process a fake transaction).

![image](https://cloud.githubusercontent.com/assets/7770631/17294392/8f68b3fa-57c4-11e6-8de8-8f46e968c68d.png)

(Since there's technically 1 left in stock, it doesn't show "backorder" on this screen)
![image](https://cloud.githubusercontent.com/assets/7770631/17294404/a8fecea8-57c4-11e6-885f-45923ac8cdf8.png)

**Comment by AnaHotaling** [comment]
Hi Kyle!

That unfortunately is not the problem. We have the 2XL and the XL in stock.
The other sizes, we don't have in stock. I set them all to Accept Back
Order/Allow Backorder But Notify Customer... and the people who have tried
to back order have been told they cannot back order in those sizes, only in
the 2XL and XL. Of course, they want M and S. Not sure what else to do,
since they are out of stock but can be back ordered... so that is what
those and the other sizes (L, XS) are set to...

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Ah, I know what the problem is then.

For those other sizes, the Stock Status is set to "Out of Stock". Even though they are set to Accept Backorders, if it is set to "Out of Stock" it will not be an option in the dropdown menu.

The smaller sizes will just need to be set to "In Stock" (As well as set to Accept Backorders) for them to be orderable.

Once I changed the Medium size to that on your Staging Site I was able to select "Medium" and it was added to my Cart while showing me that it was on Backorder.

[More details](https://wordpress.org/support/topic/products-out-of-stock-cannot-be-bought#post-5497373)

**Comment by AnaHotaling** [comment]
That darned WooCommerce. So even though it's out of stock, we have to note
that it's in stock? Okay! Not quite intuitive, but at least I understand
now! Thanks!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
Ahaha, yeah. Not very intuitive unfortunately. 

No problem!
