### ISSUE TITLE
Countdown Clock Not Showing Anything

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#84]
Both countdown clocks (primary and homepage right) are showing Next Event Coming Soon! instead of the Detroit Goddess, which is Sunday. Can someone go give it a jump start, please? I went into Widgets but I no longer have the option of setting which event should show up...

**Comment by AnaHotaling** [comment]
Ugh! The race is over and the next event should show. Although actually, I do believe Eva wants Scare for Care to be the next one instead of Defeat Depression Dash. I'm guessing that it's the date settings for Heart MI Run that is throwing the countdown clock off. Didn't this event do that last year, too? Ugh. I know we want to keep the Heart MI Run up high on the events calendar so people will see it and sign up, but I also know that we want an actual event on the Countdown Clock. Can you help set it to Scare?

**Comment by d4mation** [comment]
I have determined what the problem is!

The reason this is happening is that Widget grabs the Next Event based on its END DATE but decides whether to show it or not based on its START DATE.

The way that the Heart MI Run is set up is that the Start Date was September 15th and the End Date is in December. This means there are 0 Seconds "left" until it starts, but since it lasts until December it doesn't skip ahead to show the next one.

If the End Date for the Heart MI Run is changed accordingly (I figure it was meant to just be a single day, like most other events), this problem will resolve itself!

![image](https://cloud.githubusercontent.com/assets/7770631/18640365/ca56ddf8-7e65-11e6-8f74-a1b7f6dfaff6.png)

**Comment by d4mation** [comment]
But if you want it to show "Scare" for the Countdown rather than the Defeat Depression Dash (Which is the next event, chronologically), you will need to change the settings to the following:

![image](https://cloud.githubusercontent.com/assets/7770631/18640669/2177445a-7e67-11e6-9b9a-16cf47ed30ce.png)

Just remember that you will want to change it back to "Next Event" before the date for "Scare" hits so that it will be ready for the next one!

Appearance -> Customize 

or 

Appearance -> Widgets

**Comment by AnaHotaling** [comment]
Actually, Heart Mi Run started on the 15th and continues through December
whatever it was... it's a virtual run and people have that span of time to
sign up and complete the run. But it's clogging up the works!

And thanks for showing me how to work the pull down! Guess I just totally
missed that the Single Event choice would give me a sub menu!

Ana Hotaling
Director of Inbound Marketing, Epic Races
p: 734-585-7101 a: 600 S. Wagner Rd., Ann Arbor, MI 48103
s: http://www.epicraces.com e: ana@epicraces.com
http://facebook.com/epicracesevents http://epicraces http://epicraces

https://newoldstamp.com/editor/

**Comment by d4mation** [comment]
No problem!

I think that considering the Virtual Runs are a bit of an outlier as far as the races go, it may be best to just manually set a Race like you are doing for the "Scare for CARE" Event until the End Date has passed for the Virtual Run. Just be sure to change it for both Primary and Home Page right!
