### ISSUE TITLE
Ann Arbor Marathon listing

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#88]
Hello! Every now and then (yesterday afternoon, for instance, and two days ago, but not now) the Ann Arbor Marathon ends up at the very top of the listing on Home Page -> Events Pull Down Menu -> Run. It's fine now, but it pops up there at the very top regardless of its date every now and then.

Similarly, I just clicked "View All Events in This Category" under Run in the Events pull down, and the Ann Arbor Marathon is listed at the very top, even though there is an event before it.

And I spoke too soon. The marathon is at the top of the Events -> Run pulldown again.

**Comment by AnaHotaling** [comment]
Updating this. The Marathon is still the top listing (Pi Run should now be at the top, with the Marathon after it). The A2 Turkey Trot does not show up at all (scheduled for Nov. 11, 2017). Help!

**Comment by d4mation** [comment]
Turns out it was due to the Event being set as "Sticky", which means that it is always at the top.

![image](https://cloud.githubusercontent.com/assets/7770631/20484590/d2afbc2c-afc5-11e6-8d59-2c2209c16c2a.png)

That setting is only meant to affect the Month View, but it seems to be effecting the query that creates the Events Menu as well. Is there a reason that it was set to Sticky? If so, I can see if we can get the Menu to ignore the Sticky setting.

**Comment by AnaHotaling** [comment]
LOL, went to unsticky it and it's being edited... thanks! But that still leaves why the 2017 A2 Turkey Trot isn't showing up on the Run events. The last thing listed is Hot Cocoa...

**Comment by d4mation** [comment]
Ah, sorry, looks like I had it open in another tab still. I went ahead and fixed that for you.

As for the A2 Turkey Trot, it appears that it is set to have ended two days ago. I think that's why it isn't showing up as all the other events are in 2017.

![image](https://cloud.githubusercontent.com/assets/7770631/20493740/02754d1a-afe8-11e6-91f8-d0a46a3c5b00.png)

**Comment by AnaHotaling** [comment]
Yep, all my changes disappeared and I had to input them again! Glad I took
screenshots this time!!!
