### ISSUE TITLE
Add Ski events category to main events navigation

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_EPIC#9]
In the header there is a dropdown with links and lists for events by category. Currently there are nine categories. We need to add Ski which will make ten categories. Also we need to test and ensure the dropdown doesn't get covered by the home page content since it will be taller. Adjust styling as necessary for best fit.

**Comment by d4mation** [comment]
I tested the navigation on a lot of common resolutions and had no problems. 

I was only able to cause it to act strange if I constantly resized the window without refreshing on the Home Page due to how the Main Image in the Header works.

I took this screenshot before modifying `functions/theme-functions.php`, so it is now set to use `icon-ski` for its icon.

This is all on my local install.

![image](https://cloud.githubusercontent.com/assets/7770631/11688093/6c3cb384-9e58-11e5-87cb-e6a1d5ba8154.png)
