### ISSUE TITLE
Problem with New Pricing Table

### ISSUE THREAD

**Issue by AnaHotaling** [realbig/RBM_TH_EPIC#99]
Went to start updating the event pages to use the new pricing table. I started with the Original A2 Turkey Trot. I input all the events, pricing, deadline dates, etc., clicked Update, then went to see what it looked like on the site. All that shows are the final prices (the ones for Race-Weekend Registration) with today's date as a deadline. I went back to edit, and there's nothing I can figure out to fix. Please take a look!!

**Comment by d4mation** [comment]
Fixed it up for you!

The reason today's date was showing was because an End Date wasn't set and it expected one, but I added a bit to the code so that if it is the last Price Point of the Table (So, Race Day prices), it doesn't require a Date. This also makes it a bit more similar to your old Tables.

The other rows are now showing once again as well. The fix is live on your site!
